name: test data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: install environment
      run: |
        #curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        #bash Miniconda3-latest-Linux-x86_64.sh -b
        #conda create -n phoible -c conda-forge r=4 r-readr r-dplyr r-testthat r-knitr
        #eval "$(conda shell.bash hook)"
        #conda init bash
        #conda activate phoible
        echo "deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/" | sudo tee -a /etc/apt/sources.list > /dev/null
        sudo apt update
        sudo apt install -y r-base r-cran-dplyr r-cran-readr r-cran-testthat r-cran-knitr
        #sudo Rscript --verbose -e "install.packages(c('testthat', 'knitr', 'readr', 'dplyr'))"
    - name: test-data
      working-directory: tests
      run: |
        Rscript --verbose -e "testthat::test_dir('.')"
