name: test data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: install conda
      run: |
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b
    - name: update conda
      run: conda update -n base conda
    - name: make new environment
      run: conda create -n phoible -c conda-forge r=4 r-readr r-dplyr r-testthat r-withr r-knitr
    - name: run tests
      working-directory: tests
      run: |
        eval "$(conda shell.bash hook)"
        conda activate phoible
        Rscript -e "testthat::test_dir('.', stop_on_failure=TRUE)"
