name: test data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: install conda
      run: |
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b
        eval "$(conda shell.bash hook)"
    - name: update conda
      run: |
        conda update -n base conda
    - name: install new environment
      run: |
        conda create -n phoible -c conda-forge r=4 r-readr r-dplyr r-testthat r-knitr
        conda activate phoible
        #sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        #sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
        #sudo apt update
        #sudo apt install -y r-base r-cran-dplyr r-cran-readr r-cran-testthat r-cran-knitr
        #sudo Rscript --verbose -e "install.packages(c('testthat', 'knitr', 'readr', 'dplyr'))"
    - name: run tests
      working-directory: tests
      run: |
        Rscript --verbose -e "testthat::test_dir('.')"
