name: test data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  pull-requests: write

jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: prefix-dev/setup-pixi@v0.10.1
        with:
          pixi-version: v0.66.0
          activate-environment: "ci"
      - name: run tests
        working-directory: tests
        run: |
            Rscript -e "testthat::test_dir('.', filter = \"^(?test-phoenemes)\", stop_on_failure = TRUE)"
      - name: run feature test (write to PR comment)
        working-directory: tests
        run: |
          Rscript -e "testthat::test_file('test-phonemes.R', reporter = \"summary\")" > phoneme_feature_test_results.txt 2>&1 || true
      - name: comment on PR
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body-file phoneme_feature_test_results.txt 
