name: test data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: install mamba
      run: |
        curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
        bash Mambaforge-$(uname)-$(uname -m).sh -b
    - name: make new environment
      run: mamba create -n phoible r=4 r-readr r-dplyr==1.1.1 r-testthat r-withr r-knitr r-purrr
    - name: run tests
      working-directory: tests
      run: |
        eval "$(mamba shell.bash hook)"
        mamba activate phoible
        Rscript -e "testthat::test_dir('.', stop_on_failure=TRUE)"
