name: test data

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: install environment
      run: |
        #curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        #bash Miniconda3-latest-Linux-x86_64.sh -b
        #conda create -n phoible -c conda-forge r=4 r-tidyverse r-testthat r-knitr
        #eval "$(conda shell.bash hook)"
        #conda activate phoible
        apt install r-base r-base-core
        Rscript --verbose -e "install.packages(c('testthat', 'knitr', 'tidyverse'))"
    - name: test-data
      working-directory: tests
      run: |
        Rscript --verbose -e "testthat::test_dir('.')"
